projet-mdr/Controllers/ConfigurationController.cs
using DAL;
using Model;
using projet_mdr.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projet_mdr.Controllers
{
    public class ConfigurationController : Controller
    {
        // GET: Configuration
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MailTemplateConf()
        {
            List<MailTemplate> _listMailTemplates;

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                _listMailTemplates = gdd.DepotMailTemplates.ListerTemplates();
            }

            ViewBag.ListeTemplates = _listMailTemplates;
            ViewBag.SelectListeTemplates = _listMailTemplates.Select(m => new SelectListItem { Value = m.Id.ToString(), Text = m.Nom }).ToList();

            return View();
        }

        public ActionResult ComboCandidatureConf()
        {

            List<CandidatureExperience> listeXP;
            List<CandidatureProvenance> listePro;
            List<CandidaturePoste> listePoste;

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                listeXP = gdd.DepotCandidatureExperience.ListerExperiences();
                listePro = gdd.DepotCandidatureProvenance.ListerProvenances();
                listePoste = gdd.DepotCandidaturePoste.ListerPostes();
            }

            ViewBag.ListePoste = listePoste;
            ViewBag.ListeExperience = listeXP;
            ViewBag.ListeProvenance = listePro;

            return View();
        }

        public ActionResult SupprimerExperience(int id)
        {

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                gdd.DepotCandidatureExperience.Delete(gdd.DepotCandidatureExperience.ExperienceParId(id));
                gdd.DepotCandidatureExperience.PersistChanges();
            }

            return RedirectToAction("ComboCandidatureConf");
        }

        public ActionResult AjouterExperience(CandidatureExperience experience)
        {

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                gdd.DepotCandidatureExperience.Add(experience);
                gdd.DepotCandidatureExperience.PersistChanges();
            }

            return RedirectToAction("ComboCandidatureConf");

        }

        public ActionResult SupprimerPoste(int id)
        {

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                gdd.DepotCandidaturePoste.Delete(gdd.DepotCandidaturePoste.PosteParId(id));
                gdd.DepotCandidaturePoste.PersistChanges();
            }

            return RedirectToAction("ComboCandidatureConf");
        }

        public ActionResult AjouterPoste(CandidaturePoste poste)
        {

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                gdd.DepotCandidaturePoste.Add(poste);
                gdd.DepotCandidaturePoste.PersistChanges();
            }

            return RedirectToAction("ComboCandidatureConf");

        }

        public ActionResult SupprimerProvenance(int id)
        {

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                gdd.DepotCandidatureProvenance.Delete(gdd.DepotCandidatureProvenance.ProvenanceParId(id));
                gdd.DepotCandidatureProvenance.PersistChanges();
            }

            return RedirectToAction("ComboCandidatureConf");
        }

        public ActionResult AjouterProvenance(CandidatureProvenance provenance)
        {
  
            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                gdd.DepotCandidatureProvenance.Add(provenance);
                gdd.DepotCandidatureProvenance.PersistChanges();
            }

            return RedirectToAction("ComboCandidatureConf");

        }

        public ActionResult SupprimerMailTemplate(int id)
        {
            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                gdd.DepotMailTemplates.Delete(gdd.DepotMailTemplates.MailTemplateParId(id));
                gdd.DepotMailTemplates.PersistChanges();
            }

            return RedirectToAction("MailTemplateConf");
        }

        public ActionResult AjouterMailTemplate(MailTemplate template)
        {

            if (!ModelState.IsValid)
            {
                List<MailTemplate> _listMailTemplates;

                using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
                {
                    _listMailTemplates = gdd.DepotMailTemplates.ListerTemplates();
                }

                ViewBag.ListeTemplates = _listMailTemplates;
                ViewBag.SelectListeTemplates = _listMailTemplates.Select(m => new SelectListItem { Value = m.Id.ToString(), Text = m.Nom }).ToList();

                return View("MailTemplateConf",template);
            }

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                gdd.DepotMailTemplates.Add(template);
                gdd.DepotMailTemplates.PersistChanges();
            }

            return RedirectToAction("MailTemplateConf");

        }
    }
}

projet-mdr/Views/Configuration/ComboCandidatureConf.cshtml
@using Model
@{
    ViewBag.Title = "ComboCandidatureConf";
}


<div class="container" style="margin-top:20px">   
    <div class="panel panel-default">
        <div class="panel-heading">
            Experiences
        </div>
        <div class="panel-body">
            <div class="col-md-6">
                <table class="table table-hover table-condensed">
                    @foreach (CandidatureExperience exp in ViewBag.ListeExperience)
                    {
                        <tr>
                            <td class="col-md-10">
                                @exp.Intitule
                            </td>
                            <td class="col-md-2">
                                <a href="/Configuration/SupprimerExperience/@exp.Id"><span class="glyphicon glyphicon-remove" aria-hidden="true" style="font-size:12px;color:red"></span></a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <div class="col-md-6">
                @using (Html.BeginForm("AjouterExperience", "Configuration", FormMethod.Post, new { id = "experience" }))
            {
                    <div class="form-group">
                        <div class="col-md-2" style="text-align:right">
                            @Html.Label("Intitulé", htmlAttributes: new { @class = "control-label" })
                            <span style="color:red">*</span>
                        </div>
                        <div class="col-md-8">
                            <input name="Intitule" class="form-control text-box single-line" id="experienceIntitule" type="text" value="">
                        </div>
                        <div class="col-md-2">
                            <a onclick='verifandsave("experience")' class="btn">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true" style="font-size:20px"></span>
                            </a>
                        </div>

                    </div>

                }
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            Postes
        </div>
        <div class="panel-body">
            <div class="col-md-6">
                <table class="table table-hover table-condensed">
                    @foreach (CandidaturePoste exp in ViewBag.ListePoste)
            {
                        <tr>
                            <td class="col-md-10">
                                @exp.Intitule
                            </td>
                            <td class="col-md-2">
                                <a href="/Configuration/SupprimerPoste/@exp.Id"><span class="glyphicon glyphicon-remove" aria-hidden="true" style="font-size:12px;color:red"></span></a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <div class="col-md-6">
                @using (Html.BeginForm("AjouterPoste", "Configuration", FormMethod.Post, new { id = "poste" }))
                {
                    <div class="form-group">
                        <div class="col-md-2" style="text-align:right">
                            @Html.Label("Intitulé", htmlAttributes: new { @class = "control-label" })
                            <span style="color:red">*</span>
                        </div>
                        <div class="col-md-8">
                            <input name="Intitule" class="form-control text-box single-line" id="posteIntitule" type="text" value="">
                        </div>
                        <div class="col-md-2">
                            <a onclick='verifandsave("poste")' class="btn">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true" style="font-size:20px"></span>
                            </a>
                        </div>
                    </div>

                }
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            Provenances
        </div>
        <div class="panel-body">
            <div class="col-md-6">
                <table class="table table-hover table-condensed">
                    @foreach (CandidatureProvenance exp in ViewBag.ListeProvenance)
            {
                        <tr>
                            <td class="col-md-10">
                                @exp.Intitule
                            </td>
                            <td class="col-md-2">
                                <a href="/Configuration/SupprimerProvenance/@exp.Id"><span class="glyphicon glyphicon-remove" aria-hidden="true" style="font-size:12px;color:red"></span></a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <div class="col-md-6">
                @using (Html.BeginForm("AjouterProvenance", "Configuration", FormMethod.Post, new { id = "provenance" }))
                {
                    <div class="form-group">
                        <div class="col-md-2" style="text-align:right">
                            @Html.Label("Intitulé", htmlAttributes: new { @class = "control-label" })
                            <span style="color:red">*</span>
                        </div>
                        <div class="col-md-8">
                            <input name="Intitule" class="form-control text-box single-line" id="provenanceIntitule" type="text" value="">
                        </div>
                        <div class="col-md-2">
                            <a onclick='verifandsave("provenance")' class="btn">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true" style="font-size:20px"></span>
                            </a>
                        </div>
                    </div>

                }
            </div>
        </div>
    </div>
</div>

projet-mdr/Views/Configuration/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="container">
    <h2>Configuration</h2>



    <div>@Html.ActionLink("Configuration des templates de mail", "MailTemplateConf")</div>
    <div>@Html.ActionLink("Configuration des listes déroulantes de candidature", "ComboCandidatureConf")</div>
</div>

projet-mdr/Views/Configuration/MailTemplateConf.cshtml
@using Model
@model MailTemplate
@{
    ViewBag.Title = "MailTemplateConf";
}
<div style="padding-right: 15px;padding-left: 15px;margin-right: auto;margin-left: auto;width:90%">
    <div class="col-md-6" style="margin-top:20px">
        @{Html.RenderPartial("~/Views/Configuration/_créerMailTemplate.cshtml", Model);}
    </div>
    <div class="col-md-6" style="margin-top:20px">
        <div class="panel panel-default">
            <div class="panel-heading">
                Détail et suppression
            </div>
            <div class="panel-body">
                <div style="margin-bottom:15px">
                    @Html.DropDownList("selectmail", ViewBag.SelectListeTemplates as List<SelectListItem>, "Sélectionner un template de mail", new { @class = "form-control" })
                </div>
                @foreach (MailTemplate mail in ViewBag.ListeTemplates)
                {
                    <div id=@("mail"+mail.Id) class="maildiv" style="display:none">
                        <div>
                            <label>Nom :</label>
                            <span>@mail.Nom</span>
                        </div>
                        <div>
                            <label>Objet :</label>
                            <span>@mail.Objet</span>
                        </div>
                        <div style="margin-bottom:15px">
                            <label>Contenu du mail :</label>
                            <div>@(new HtmlString((mail.Corps ?? "").Replace(Environment.NewLine, "<br />")))</div>
                        </div>
                        <a href="/Configuration/SupprimerMailTemplate/@mail.Id"><span class="glyphicon glyphicon-remove" aria-hidden="true" style="font-size:12px;color:red"></span>Supprimer le template</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

projet-mdr/Views/Configuration/_créerMailTemplate.cshtml
@model Model.MailTemplate

<div class="panel panel-default">
    <div class="panel-heading">
        Ajouter un Template de Mail
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("AjouterMailTemplate", "Configuration", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Objet, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Objet, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Objet, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Corps, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Corps, htmlAttributes: new { @class = "form-control", rows = 7 })
                        @Html.ValidationMessageFor(model => model.Corps, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>

            </div>
        }
    </div>
</div>