projet-mdr/Controllers/AnnoncesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using projet_mdr.ViewModels;
using DAL;
using DAL.Depots;
using Extensions;

namespace projet_mdr.Controllers
{
    public class AnnoncesController : Controller
    {
        // GET: Annonces
        public ActionResult Index(string filters, string selectauteur)
        {
            AnnoncesVueModele AVM = new AnnoncesVueModele();
            List<Annonce> ListAnnonces;
            List<string> ListCreePar;

            // Requêtage BDD
            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                ListAnnonces = (String.IsNullOrWhiteSpace(filters) && String.IsNullOrWhiteSpace(selectauteur)) ?
                    gdd.DepotAnnonces.RechercherCinqDernieresAnnonces()
                    : gdd.DepotAnnonces.RechercheAnnonceParTitreouRefouAuteur(selectauteur, filters);

                ListCreePar = gdd.DepotAnnonces.RecupereTousLesAuteurs();
            }

            // Creation des listes d'objets à afficher
            AVM.ListeAnnonces = ListAnnonces.Select(l => new SelectListItem { Value = l.Id.ToString(), Text = l.Nom });
            AVM.ListeCreePar = ListCreePar.Select(l => new SelectListItem { Text = l.ToString() });

            return View(AVM);
        }

        public ActionResult Apercu(int idAnnonce)
        {
            Annonce annonceAPublier = new Annonce();

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                annonceAPublier = gdd.DepotAnnonces.RecupererAnnonceParId(idAnnonce);
            }

            return View(annonceAPublier);
        }

        public ActionResult Creer()
        {
            return View();
        }

        public ActionResult Publier(int idAnnonce)
        {
            Annonce annonceAPublier;

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                annonceAPublier = gdd.DepotAnnonces.RecupererAnnonceParId(idAnnonce);
                annonceAPublier.Statut.Intitule = "Publié";

                gdd.DepotAnnonces.Update(annonceAPublier);

                gdd.DepotAnnonces.PersistChanges();
            }

            this.AddNotification("Le statut de votre annonce est bien passé en 'publiée'", NotificationType.SUCCESS);

            return View("Apercu", annonceAPublier);
        }

        public ActionResult Editer(int? id)
        {
            Annonce AnnonceAEditer;

            if (id.HasValue == false)
            {
                return RedirectToAction("Creer");
            }
            else
            {
                using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
                {
                    AnnonceAEditer = gdd.DepotAnnonces.RecupererAnnonceParId(id.Value);
                }
            }

            if (AnnonceAEditer.Statut != null && AnnonceAEditer.Statut.Intitule == "Publié")
                this.AddNotification("Attention, vous êtes en train de modifier une annonce déjà publiée. L'enregistrer en créera une nouvelle", NotificationType.WARNING);

            return View(AnnonceAEditer);
        }

        [HttpPost]
        public ActionResult Enregistrer(List<string> texteBDT, string titreAnnonce, List<int> hiddenId, int? annonceId)
        {
            Annonce AnnonceASauvegarder;

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                if (annonceId.HasValue && annonceId.Value > 0 && gdd.DepotAnnonces.RecupererAnnonceParId(annonceId.Value).Statut.Intitule != "Publié")
                {
                    AnnonceASauvegarder = gdd.DepotAnnonces.RecupererAnnonceParId(annonceId.Value);
                }
                else
                {
                    AnnonceASauvegarder = new Annonce();
                    AnnonceASauvegarder.Statut = new AnnonceStatut() { Intitule = "En création" };
                }

                AnnonceASauvegarder.Titre = titreAnnonce;
                AnnonceASauvegarder.Nom = titreAnnonce + " " + DateTime.Now.ToShortDateString();

                List<LigneAnnonce> listeLigneAnnonce = new List<LigneAnnonce>();

                for (int i = 0; i < texteBDT.Count(); i++)
                {
                    LigneAnnonce la = new LigneAnnonce();
                    BlocDeTexte bdt;

                    if (hiddenId[i] > 0 && gdd.DepotBlocDeTexte.RechercherParId(hiddenId[i]).Texte == texteBDT[i])
                    {
                        bdt = gdd.DepotBlocDeTexte.RechercherParId(hiddenId[i]);
                    }
                    else
                    {
                        bdt = new BlocDeTexte();
                        bdt.Nom = "Interne";
                        bdt.Texte = texteBDT[i];
                        bdt.NbAcces = 0;
                        bdt.DernierAccesLe = DateTime.Now;
                        bdt.ModifieLe = DateTime.Now;
                        bdt.ModifiePar = "Jean-Mi";
                        bdt.CreeLe = DateTime.Now;
                        bdt.CreePar = "Jean-Mi";
                    }

                    la.BlocDeTexte = bdt;
                    la.Ordre = i + 1;

                    listeLigneAnnonce.Add(la);
                }

                AnnonceASauvegarder.LignesAnnonce = listeLigneAnnonce;

                if (AnnonceASauvegarder.Statut.Intitule == "En création")
                {
                    gdd.DepotAnnonces.Add(AnnonceASauvegarder);
                    AnnonceASauvegarder.Statut.Intitule = "Créé";
                }
                else
                {
                    gdd.DepotAnnonces.Update(AnnonceASauvegarder);
                }
                gdd.DepotAnnonces.PersistChanges();
            }
            int idAnnonce = AnnonceASauvegarder.Id;
            this.AddNotification("Annonce sauvegardée", NotificationType.SUCCESS);
            return RedirectToAction("Apercu", "Annonces", new { idAnnonce = idAnnonce });
        }
    }
}

projet-mdr/Controllers/BlocDeTexteController.cs
using DAL;
using DAL.Depots;
using Model;
using projet_mdr.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projet_mdr.Controllers
{
    public class BlocDeTexteController : Controller
    {
        public ActionResult Lister(string filtre, string intituletype)
        {
            InsertionBDTVueModele IVM = new InsertionBDTVueModele();
            List<BlocDeTexte> ListeBDT;
            List<TypeBDT> ListeType;

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                ListeBDT = gdd.DepotBlocDeTexte.RechercherBDTParTypeEtFiltre(intituletype, filtre);
                ListeType = gdd.DepotBDTType.ListerTypes();
            }

            IVM.ListeBDT = ListeBDT.Select(l => new SelectListItem { Value = l.Id.ToString(), Text = l.Nom.ToString() });
            IVM.ListeTypeBDT = ListeType.Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.Intitule.ToString(), Selected = (t.Intitule == intituletype) });
            IVM.filtre = filtre;

            return PartialView(IVM);
        }

        public ActionResult RecupererTexte(int? id)
        {

            if (!id.HasValue)
                return Content("");

            string content;
            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                content = gdd.DepotBlocDeTexte.RechercherParId(id.Value).Texte;
            }

            return Content(content);

        }

        public ActionResult Creer(string texte1)
        {
            List<TypeBDT> ListeType;

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                ListeType = gdd.DepotBDTType.ListerTypes();
            }

            ViewBag.ListeType = ListeType.Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.Intitule }).ToList();
            return PartialView();
        }

        public ActionResult Enregistrer(string titrebdt, string nouveautextebdt, int id)
        {
            int idBdt;

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                BlocDeTexte bdtsauvegarde = new BlocDeTexte();
                bdtsauvegarde.Nom = titrebdt;
                bdtsauvegarde.Texte = nouveautextebdt;
                bdtsauvegarde.DernierAccesLe = DateTime.Now;
                bdtsauvegarde.Type = gdd.DepotBDTType.RecupererTypeParId(id);

                gdd.DepotBlocDeTexte.Add(bdtsauvegarde);
                gdd.DepotBlocDeTexte.PersistChanges();

                idBdt = bdtsauvegarde.Id;
            }

            return Content(idBdt.ToString());

        }

        public ActionResult CreerBdtType(string nom)
        {
            if (String.IsNullOrEmpty(nom))
                return Content("");

            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                gdd.DepotBDTType.Add(new TypeBDT() {Intitule=nom});
                gdd.DepotBDTType.PersistChanges();
            }

            return Content("insertion réussie");
        }

        public ActionResult Archiver(int id)
        {
            using (GestionnaireDeDepot gdd = new GestionnaireDeDepot())
            {
                BlocDeTexte bdt = gdd.DepotBlocDeTexte.RechercherParId(id);
                bdt.Type = null;
                gdd.DepotBlocDeTexte.Update(bdt);
                gdd.DepotBlocDeTexte.PersistChanges();
            }

            return Content("réussi");
        }

    }
}

projet-mdr/Views/Annonces/Apercu.cshtml
@using Model;
@using projet_mdr.ViewModels
@model Annonce


@{
    ViewBag.Title = "Apercu";
}
<div class="container body-content">
    <h2>MenuAnnonce</h2>

    <div style="text-align:center">
        <input type="hidden" value="@Model.Id" name="annonceId" />
        @Html.Label("labelAnnonce", Model.Titre)
    </div>

    <div style="margin-top:10px; text-align:center">
        @Html.Label("bloctexte", "Contenu de l'annonce")
    </div>

    <div style="margin-top:10px;width:80%">

        <div id="blocBDT">
            @for (int i = 0; i < Model.LignesAnnonce.Count(); i++)
            {
                <div style="margin-bottom:15px">
                    @(new HtmlString(Model.LignesAnnonce.ElementAt(i).BlocDeTexte.Texte.ToString().Replace(Environment.NewLine, "<br />")))
                </div>
            }
        </div>

        <div>
            @Html.ActionLink("Publier", "Publier", "Annonces", new { idAnnonce = Model.Id }, null)
            @Html.ActionLink("Retour Accueil", "Index", "Annonces")
        </div>
    </div>


    </div>

projet-mdr/Views/Annonces/Creer.cshtml
@{
    ViewBag.Title = "Creer";
}
<div class="container body-content">
    <div class="container">

        @using (Html.BeginForm("Enregistrer", "Annonces", FormMethod.Post))
        {
            <div class="container">
                <div style="text-align:center;margin-bottom:40px" class="col-md-8">
                    <input type="hidden" value="-1" name="annonceId" />
                    <input type="hidden" value="" id="currentBdt" />
                    <h3> <label>Contenu de l'annonce</label></h3>
                </div>
            </div>

            <div class="container" style="text-align:center;margin-bottom:20px;display:block">
                <label class="col-md-3">Titre de l'annonce</label>
                <div class="col-md-3">
                    @Html.TextBox("titreAnnonce", "", new { @class = "form-control" })
                </div>
            </div>

            <div class="container">
                <div id="blocBDT" style="display:block">
                    <div id="divId1">
                        <input type="hidden" value="-1" id="inputHidden1" name="hiddenId" />
                        <div class="col-md-8">
                            @Html.TextArea("texteBDT", "", new { @class = "form-control AnnonceEditionTxtArea", id = "texte1", placeholder = "Inserer votre texte ici" })
                        </div>
                        <div class="col-md-4">
                            <input type="button" value="Sauvegarder" class="btn btn-default" onclick='EnregistrerBDT(1)' />
                            <input type="button" value="Inserer" class="btn btn-default" onclick="chargerBDT(1)" />
                        </div>
                    </div>
                </div>
            </div>

            <div class="container">
                <div class="col-md-12" style="margin-bottom:20px">
                    <input type="button" value="+" onclick="AjouterBDT()" class="btn btn-default">
                </div>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <input type="submit" value="Enregistrer Annonce" class="btn btn-default" onclick="return confirm('Enregistrer?')" />
                        <input type="button" value="Retour vers Recherche" onclick="window.location.href ='/Annonces'" class="btn btn-default" />
                    </div>

                </div>
            </div>
        }
    </div>


    <div class="modal fade" id="renderInsertionPartial">
        <div class="modal-dialog">
            <div class="modal-content" id="listerContent">
                @{Html.RenderAction("Lister", "BlocDeTexte");}
            </div>
        </div>
    </div>

    <div class="modal fade" id="renderEnregistrerPartial">
        <div class="modal-dialog">
            <div class="modal-content">
                @{Html.RenderAction("Creer", "BlocDeTexte");}
            </div>
        </div>
    </div>

</div>

projet-mdr/Views/Annonces/Editer.cshtml
@using Model;
@using projet_mdr.ViewModels;
@model Annonce

@{
    ViewBag.Title = "Editer";
}
<div class="container body-content">
    <div class="container">
        <h2 style="margin-bottom:50px">Edition de l'annonce</h2>

        @using (Html.BeginForm("Enregistrer", "Annonces", FormMethod.Post))
        {
            <div class="container">
                <div style="text-align:center;margin-bottom:40px" class="col-md-8">
                    <input type="hidden" value="@Model.Id" name="annonceId" />
                    <input type="hidden" value="" id="currentBdt" />
                    <h3> <label>Contenu de l'annonce</label></h3>
                </div>
            </div>
            <div class="container" style="text-align:center;margin-bottom:20px;display:block">
                <label class="col-md-3">Titre de l'annonce</label>
                <div class="col-md-3">
                    @Html.TextBox("titreAnnonce", Model.Titre, new { @class = "form-control" })
                </div>
            </div>

            <div class="container">

                <div id="blocBDT" style="display:block">
                    @for (int i = 1; i <= Model.LignesAnnonce.Count(); i++)
                {
                    BlocDeTexte b = Model.LignesAnnonce.ElementAt(i - 1).BlocDeTexte;

                        <div id=@("divId" + i)>

                            <br />
                            <input type="hidden" value="@b.Id" id=@("inputHidden" + i) name="hiddenId" />
                            <div class="col-md-8">
                                @Html.TextArea("texteBDT", b.Texte, new { @class = "form-control AnnonceEditionTxtArea", id = "texte" + i, placeholder = "Inserer votre texte ici" })
                            </div>
                            <div class="col-md-4">
                                <input type="button" value="Sauvegarder" class="btn btn-default" onclick='EnregistrerBDT(@i)' />
                                <input type="button" value="Inserer" class="btn btn-default" onclick="chargerBDT(@i)" />

                                @*contrôle pour ne pas ajouter de bouton "supprimer" au premier element *@
                                @if (i > 1)
                                {
                                    <input type="button" value="x" class="btn btn-default" id=@("btSupprimer" + i) onclick='SupprimerBDT(@(i))' />
                                }
                            </div>
                        </div>
                    }
                </div>

            </div>
            <div class="container">
                <div class="col-md-12" style="margin-bottom:20px">
                    <input type="button" value="+" onclick="AjouterBDT()" class="btn btn-default">
                </div>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <input type="submit" value="Enregistrer Annonce" class="btn btn-default" onclick="return confirm('Enregistrer?')" />
                        <input type="button" value="Retour vers Recherche" onclick="window.location.href ='/Annonces'" class="btn btn-default" />
                    </div>

                </div>
            </div>
        }
    </div>


    <div class="modal fade" id="renderInsertionPartial">
        <div class="modal-dialog">
            <div class="modal-content" id="listerContent">
                @{Html.RenderAction("Lister", "BlocDeTexte");}
            </div>
        </div>
    </div>

    <div class="modal fade" id="renderEnregistrerPartial">
        <div class="modal-dialog">
            <div class="modal-content">
                @{Html.RenderAction("Creer", "BlocDeTexte");}
            </div>
        </div>
    </div>

</div>

projet-mdr/Views/Annonces/Index.cshtml
@using Model;
@using projet_mdr.ViewModels

@model AnnoncesVueModele

@{
    ViewBag.Title = "Annonces";
}
<div class="container body-content">
    <div class="container" style="margin-top:20px">

        @using (Html.BeginForm("Index", "Annonces", new { filters = "" }, FormMethod.Get))
        {
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">Liste des Annonces</div>
                    <div class="panel-body">@Html.ListBox("resultats", Model.ListeAnnonces, new { style = "width:100%; min-height:260px; background:lightgrey;size:1;border-radius:20" })</div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-heading">Recherche</div>
                    <div class="panel-body">
                        <div class="form-horizontal">
                            <div style="margin-bottom:20px">
                                @Html.Label("selectauteur", "Auteur :")
                                @Html.DropDownList("selectauteur", Model.ListeCreePar, "Selectionner un auteur", new { @class = "form-control" })
                            </div>

                            <div style="margin-bottom:20px">
                                @Html.Label("filters", "Filtrer par :")
                                @Html.TextBox("filters", Request.Params["filters"], new { @class = "form-control" })
                            </div>
                            <div class="text-center">
                                <input type="submit" value="Rechercher" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Actions
                    </div>
                    <div class="panel-body">
                        <input type="button" class="btn btn-default" value="Editer l'annonce selectionnée" onclick="allerVersEdition()" />
                        <input type="button" class="btn btn-default" value="Voir le détail" onclick="allerVersApercu()" />
                        <input type="button" class="btn btn-default" value="Nouvelle annonce" onclick="window.location.href = '/Annonces/Creer'" />
                    </div>
                </div>
            </div>
        }
    </div>
    </div>